name: Build APK Buku Kas
on: push

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install semua library
        run: |
          pip install flet-cli==0.85.3
          pip install reportlab openpyxl pillow
          
      - name: Build APK
        run: flet build apk main.py --build-number 1 --verbose
        
      - name: Upload APK jadi
        uses: actions/upload-artifact@v4
        with:
          name: BukuKasSakha.apk
          path: dist/*.apk
