name: Build APK Buku Kas
on: 
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Download kode
        uses: actions/checkout@v4
        
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install Flet
        run: pip install flet-cli==0.85.3 reportlab openpyxl
        
      - name: Build APK
        run: flet build apk main.py --build-number 1 --verbose
        
      - name: Upload APK jadi
        uses: actions/upload-artifact@v4
        with:
          name: BukuKasSakha-Sultan.apk
          path: dist/*.apk
