name: Build APK Buku Kas
on:
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Cek file ada apa aja
        run: ls -la
        
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install library
        run: pip install flet-cli==0.85.3 reportlab openpyxl pillow
        
      - name: Build APK
        run: yes | flet build apk main.py --build-number 1
        
      - uses: actions/upload-artifact@v4
        with:
          name: BukuKasSakha-Sultan.apk
          path: dist/*.apk
